# NumPy Concepts & Practice

This notebook contains my practice work and exploration of different NumPy concepts. It's designed as a learning resource for anyone interested in mastering NumPy.

**Author:** Prayanshu Chourasia  
**Date:** December 2025  
**LinkedIn:** [Prayanshu Chourasia](https://www.linkedin.com/in/prayanshuchourasia01/)  
**GitHub:** [Prayanshu Chourasia/AI-ML-Notebook-Hub](https://github.com/Prayanshuchourasia-01/AI-ML-Notebook-Hub)

---

### Contents
- NumPy basics
- Array operations
- Indexing and slicing
- Reshaping

### Overview
This notebook covers fundamental NumPy concepts with practical examples and exercises. It's suitable for beginners and intermediate learners.

### Prerequisites
- Python 3.8+
- NumPy 1.20+
- Jupyter Notebook

### Usage
1. Clone this repository
2. Open the notebook in Jupyter
3. Run cells in order
4. Experiment with the code

### Contact
For questions or feedback, please reach out:
- Email: prayanshuchourasia01@gmail.com
- LinkedIn: [Prayanshu Chourasia](https://www.linkedin.com/in/prayanshuchourasia01/)

---

**Note:** This is a learning resource. Feel free to fork, reference, or use this for educational purposes.

# Importing Numpy As np

In [12]:
import numpy as np

# Numpy Array 

In [13]:
array=np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


# Using list to make numpy array

In [14]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
array=np.array([l1,l2])
print("l1 type is ",type(l1))
print("ARRAY : ")
print(array)
print("Array type is ",type(array))

l1 type is  <class 'list'>
ARRAY : 
[[1 2 3 4]
 [5 6 7 8]]
Array type is  <class 'numpy.ndarray'>


# Difference betwween numpy array and list 

In [15]:
l1 = [1,2,3,4]

array=np.array(l1)

print("l1 type is ",type(l1))
print(l1*2) # as we can see that this simple list multiple the whole list with the number(2) which create duplicase

print("Array type is ",type(array))
print(array*2)  # as we can see that this numpy array will multiple each element with the number(2)

l1 type is  <class 'list'>
[1, 2, 3, 4, 1, 2, 3, 4]
Array type is  <class 'numpy.ndarray'>
[2 4 6 8]


# Working and Check of Multi-Dimentional Array

In [16]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
arr = np.array("A")
array=np.array(l1)
array2=np.array([l1,l2])


print("Array type is ",type(array))
print(arr.ndim)
print(array.ndim)  # ndim is a numpy function which return the value of number of dimenstional in a array 
print(array2.ndim) 

Array type is  <class 'numpy.ndarray'>
0
1
2


# Finding the Depth , Row , Columns using Shape Attribute 

In [17]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

arr = np.array("A")
array=np.array(l1)
array2=np.array([l1,l2])
array3=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]])

print("Array type is ",type(array))
print(arr.shape)
print(array.shape)  # shape attribute returns the tuple of value in order of (Depth,Row,Column)
print(array2.shape)
print(array3.shape)

Array type is  <class 'numpy.ndarray'>
()
(4,)
(2, 4)
(3, 3, 4)


# Access The Element in the numpy array using chain indexing.(same as list)

In [18]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([l1,l2,l3])
print(array[0][2]) # as we can see we are using chain indexing which is same as access the element in the list 

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array[0][2]) # here frist 0 represent the 0th index list which is [l1,l2,l3] and second value 2
#                    represents the 1th index of the 0th index list which is l3
print(array[0][2][2]) # here we go in more depth to access a indivdual element.

3
[ 9 10 11 12]
11


# Access the Element using Multi-Dimensational Indexing (specially for numpy array) Fancy Indexing 

In [20]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([l1,l2,l3])
print(array[0,2]) # as we can see we are using multi dimensational indexing which we specailly use in numpy array 

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array[0,2]) # here frist 0 represent the 0th index list which is [l1,l2,l3] and second value 2
#                    represents the 1th index of the 0th index list which is l3
print(array[0,2,2]) # here we go in more depth to access a indivdual element.

3
[ 9 10 11 12]
11


# Access The element and concating (can we done with strings too )

In [21]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
word = array[0][1][2] + array[2][1][0]
print(f"{array[0][1][2]} + {array[2][1][0]}")
print(word)

7 + 5
12


# Array Slicing [start:stop:step]

In [22]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 

# To Slice the Array order is: [start:stop:step]
print(array,"\n")
print(array[1:4:2])


print(array[1:,4:-2])


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]]

 [[ 9 10 11 12]
  [ 5  6  7  8]
  [ 1  2  3  4]]] 

[[[ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]]]
[]


# Using Default Values - ZERO in full matrix

In [23]:
print("\n")
zeros_arr = np.zeros(3)
print(zeros_arr)
print("\n")
zeros_arr = np.zeros((3,3))
print(zeros_arr)
print("\n")
zeros_arr = np.zeros((3,3,3))
print(zeros_arr)



[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# Using Default Values - ONES in full matrix

In [24]:
print("\n")
ones_arr = np.ones(3)
print(ones_arr)
print("\n")
ones_arr = np.ones((3,3))
print(ones_arr)
print("\n")
ones_arr = np.ones((3,3,3))
print(ones_arr)



[1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#Using Default Values - ANY (value) in full matrix

In [25]:
print("\n")
any_arr = np.full(3,5)
print(any_arr)
print("\n")
any_arr = np.full((3,3),7)
print(any_arr)
print("\n")
any_arr = np.full((3,3,3),4)
print(any_arr)



[5 5 5]


[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]]


# Creating the Sequence of numbers using Numpy arrange()

In [26]:
# arange(start,stop,step) --- it returns the numpy array of numbers 
arr = np.arange(1,20,3)
print(arr)

arr = np.arange(0,51,5)
print(arr)

arr = np.arange(1,20)
print(arr)

[ 1  4  7 10 13 16 19]
[ 0  5 10 15 20 25 30 35 40 45 50]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Creating Identity Matrices using eye()

In [27]:
ide_mat = np.eye(4) # eye(size) --- it returns the identity matrix which have ones(1) in the diagonals only and zero in whole matrixs
print(ide_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Finding The Size of the array using size attrbute

In [28]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we have multi dimensational array..
print(array.size)  # size is not a function so we dont use () in this.. 

36


# How to check the datatype of the array using dtype

In [29]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array.dtype)

arr=np.array([1.1,2.2,34])
print(arr.dtype)

int64
float64


# How to change the Datatype of the array -- using astype()

In [30]:
 # astype(newtype) -- it returns the array of new datatype which is written in the parameters 
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]])
array=array.astype(float)
print(array)
print(array.dtype)

arr=np.array([1.1,2.2,34])
arr = arr.astype(int)
print(arr)
print(arr.dtype)


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [ 1.  2.  3.  4.]]

 [[ 9. 10. 11. 12.]
  [ 5.  6.  7.  8.]
  [ 1.  2.  3.  4.]]]
float64
[ 1  2 34]
int64



# Numpy Arthimatics Operations : BASIC 
## + - * / ** % 

In [31]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([l1,l2,l3])
print(array+2)
print(array*5)
print(array**2)


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


# Numpy Aggregation Functions 

In [32]:

array = np.array([10,20,30,40,50])
print(np.sum(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))
print(np.mean(array))
print(np.var(array))


150
10
50
14.142135623730951
30.0
200.0


# Numpy Boolean Masking Or Filtering 

In [33]:

arr=np.array([10,20,30,40,50])
print(arr[10<25])  #  we can use these value as a placeholder and can be used as conditions (optionals)

print(arr[arr>40]) # boolean masking -- it will return the values of the array based on the condition.

[[10 20 30 40 50]]
[50]


 # Numpy Reshaping Of array -- using reshape()

In [40]:

# reshaping(row,column) specify new shape 
# in this we change the dimensations only, and it does'nt increase or decrease the element in the array.
# this works only when dimensations matchs , and doesnt copy the arra... its creates a view.. 
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
print(arr)
print("\n")
arr=arr.reshape(3,2)
print(arr)


[[1 2 3]
 [4 5 6]]


[[1 2]
 [3 4]
 [5 6]]


# Flattening Arrays -- using Ravel() & Flatten() in Numpy 

In [44]:
# Ravel() -- it returns a view.. it changes the original arr , flatten() -- it reutrns a copy
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ravel())
print(arr.view()) # to get the original view of arr 
print(arr.flatten())

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# Advance Concepts of Numpy : Here we will Add, Remove , Split 

#

#