# NumPy Concepts & Practice

This notebook contains my practice work and exploration of different NumPy concepts. It's designed as a learning resource for anyone interested in mastering NumPy.

**Author:** Prayanshu Chourasia  
**Date:** December 2025  
**LinkedIn:** [Prayanshu Chourasia](https://www.linkedin.com/in/prayanshuchourasia01/)  
**GitHub:** [Prayanshu Chourasia/AI-ML-Notebook-Hub](https://github.com/Prayanshuchourasia-01/AI-ML-Notebook-Hub)

---

### Contents
- NumPy basics
- Array operations
- Indexing and slicing
- Reshaping

### Overview
This notebook covers fundamental NumPy concepts with practical examples and exercises. It's suitable for beginners and intermediate learners.

### Prerequisites
- Python 3.8+
- NumPy 1.20+
- Jupyter Notebook

### Usage
1. Clone this repository
2. Open the notebook in Jupyter
3. Run cells in order
4. Experiment with the code

### Contact
For questions or feedback, please reach out:
- Email: prayanshuchourasia01@gmail.com
- LinkedIn: [Prayanshu Chourasia](https://www.linkedin.com/in/prayanshuchourasia01/)

---

**Note:** This is a learning resource. Feel free to fork, reference, or use this for educational purposes.

# Importing Numpy As np

In [1]:
import numpy as np

# Numpy Array 

In [13]:
array=np.array([1,2,3,4])
print(array)
print(type(array))

[1 2 3 4]
<class 'numpy.ndarray'>


# Using list to make numpy array

In [14]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
array=np.array([l1,l2])
print("l1 type is ",type(l1))
print("ARRAY : ")
print(array)
print("Array type is ",type(array))

l1 type is  <class 'list'>
ARRAY : 
[[1 2 3 4]
 [5 6 7 8]]
Array type is  <class 'numpy.ndarray'>


# Difference betwween numpy array and list 

In [15]:
l1 = [1,2,3,4]

array=np.array(l1)

print("l1 type is ",type(l1))
print(l1*2) # as we can see that this simple list multiple the whole list with the number(2) which create duplicase

print("Array type is ",type(array))
print(array*2)  # as we can see that this numpy array will multiple each element with the number(2)

l1 type is  <class 'list'>
[1, 2, 3, 4, 1, 2, 3, 4]
Array type is  <class 'numpy.ndarray'>
[2 4 6 8]


# Working and Check of Multi-Dimentional Array

In [16]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
arr = np.array("A")
array=np.array(l1)
array2=np.array([l1,l2])


print("Array type is ",type(array))
print(arr.ndim)
print(array.ndim)  # ndim is a numpy function which return the value of number of dimenstional in a array 
print(array2.ndim) 

Array type is  <class 'numpy.ndarray'>
0
1
2


# Finding the Depth , Row , Columns using Shape Attribute 

In [17]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

arr = np.array("A")
array=np.array(l1)
array2=np.array([l1,l2])
array3=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]])

print("Array type is ",type(array))
print(arr.shape)
print(array.shape)  # shape attribute returns the tuple of value in order of (Depth,Row,Column)
print(array2.shape)
print(array3.shape)

Array type is  <class 'numpy.ndarray'>
()
(4,)
(2, 4)
(3, 3, 4)


# Access The Element in the numpy array using chain indexing.(same as list)

In [18]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([l1,l2,l3])
print(array[0][2]) # as we can see we are using chain indexing which is same as access the element in the list 

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array[0][2]) # here frist 0 represent the 0th index list which is [l1,l2,l3] and second value 2
#                    represents the 1th index of the 0th index list which is l3
print(array[0][2][2]) # here we go in more depth to access a indivdual element.

3
[ 9 10 11 12]
11


# Access the Element using Multi-Dimensational Indexing (specially for numpy array) Fancy Indexing 

In [20]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([l1,l2,l3])
print(array[0,2]) # as we can see we are using multi dimensational indexing which we specailly use in numpy array 

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array[0,2]) # here frist 0 represent the 0th index list which is [l1,l2,l3] and second value 2
#                    represents the 1th index of the 0th index list which is l3
print(array[0,2,2]) # here we go in more depth to access a indivdual element.

3
[ 9 10 11 12]
11


# Access The element and concating (can we done with strings too )

In [21]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
word = array[0][1][2] + array[2][1][0]
print(f"{array[0][1][2]} + {array[2][1][0]}")
print(word)

7 + 5
12


# Array Slicing [start:stop:step]

In [22]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]
array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 

# To Slice the Array order is: [start:stop:step]
print(array,"\n")
print(array[1:4:2])


print(array[1:,4:-2])


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]]

 [[ 9 10 11 12]
  [ 5  6  7  8]
  [ 1  2  3  4]]] 

[[[ 5  6  7  8]
  [ 9 10 11 12]
  [ 1  2  3  4]]]
[]


# Using Default Values - ZERO in full matrix

In [23]:
print("\n")
zeros_arr = np.zeros(3)
print(zeros_arr)
print("\n")
zeros_arr = np.zeros((3,3))
print(zeros_arr)
print("\n")
zeros_arr = np.zeros((3,3,3))
print(zeros_arr)



[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# Using Default Values - ONES in full matrix

In [24]:
print("\n")
ones_arr = np.ones(3)
print(ones_arr)
print("\n")
ones_arr = np.ones((3,3))
print(ones_arr)
print("\n")
ones_arr = np.ones((3,3,3))
print(ones_arr)



[1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# Using Default Values - ANY (value) in full matrix

In [25]:
print("\n")
any_arr = np.full(3,5)
print(any_arr)
print("\n")
any_arr = np.full((3,3),7)
print(any_arr)
print("\n")
any_arr = np.full((3,3,3),4)
print(any_arr)



[5 5 5]


[[7 7 7]
 [7 7 7]
 [7 7 7]]


[[[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]

 [[4 4 4]
  [4 4 4]
  [4 4 4]]]


# Creating the Sequence of numbers using Numpy arange()

In [26]:
# arange(start,stop,step) --- it returns the numpy array of numbers 
arr = np.arange(1,20,3)
print(arr)

arr = np.arange(0,51,5)
print(arr)

arr = np.arange(1,20)
print(arr)

[ 1  4  7 10 13 16 19]
[ 0  5 10 15 20 25 30 35 40 45 50]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Creating Identity Matrices using eye()

In [27]:
ide_mat = np.eye(4) # eye(size) --- it returns the identity matrix which have ones(1) in the diagonals only and zero in whole matrixs
print(ide_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Finding The Size of the array using size attrbute

In [28]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we have multi dimensational array..
print(array.size)  # size is not a function so we dont use () in this.. 

36


# How to check the datatype of the array using dtype

In [29]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]]) # here we added more list 
print(array.dtype)

arr=np.array([1.1,2.2,34])
print(arr.dtype)

int64
float64


# How to change the Datatype of the array -- using astype()

In [30]:
 # astype(newtype) -- it returns the array of new datatype which is written in the parameters 
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([[l1,l2,l3],[l2,l3,l1],[l3,l2,l1]])
array=array.astype(float)
print(array)
print(array.dtype)

arr=np.array([1.1,2.2,34])
arr = arr.astype(int)
print(arr)
print(arr.dtype)


[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [ 1.  2.  3.  4.]]

 [[ 9. 10. 11. 12.]
  [ 5.  6.  7.  8.]
  [ 1.  2.  3.  4.]]]
float64
[ 1  2 34]
int64



# Numpy Arthimatics Operations : BASIC 
## + - * / ** % 

In [31]:
l1 = [1,2,3,4]
l2=[5,6,7,8]
l3 =[9,10,11,12]

array=np.array([l1,l2,l3])
print(array+2)
print(array*5)
print(array**2)


[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


# Numpy Aggregation Functions 

In [32]:

array = np.array([10,20,30,40,50])
print(np.sum(array))
print(np.min(array))
print(np.max(array))
print(np.std(array))
print(np.mean(array))
print(np.var(array))


150
10
50
14.142135623730951
30.0
200.0


# Numpy Boolean Masking Or Filtering 

In [33]:

arr=np.array([10,20,30,40,50])
print(arr[10<25])  #  we can use these value as a placeholder and can be used as conditions (optionals)

print(arr[arr>40]) # boolean masking -- it will return the values of the array based on the condition.

[[10 20 30 40 50]]
[50]


 # Numpy Reshaping Of array -- using reshape()

In [40]:

# reshaping(row,column) specify new shape 
# in this we change the dimensations only, and it does'nt increase or decrease the element in the array.
# this works only when dimensations matchs , and doesnt copy the arra... its creates a view.. 
arr = np.array([1,2,3,4,5,6])
arr = arr.reshape(2,3)
print(arr)
print("\n")
arr=arr.reshape(3,2)
print(arr)


[[1 2 3]
 [4 5 6]]


[[1 2]
 [3 4]
 [5 6]]


# Flattening Arrays -- using Ravel() & Flatten() in Numpy 

In [44]:
# Ravel() -- it returns a view.. it changes the original arr , flatten() -- it reutrns a copy
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.ravel())
print(arr.view()) # to get the original view of arr 
print(arr.flatten())

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


# Advance Concepts of Numpy : Here we will Add, Remove , Split 

In [15]:
# INSERT (array,index,value,asix)           axis : 0 -> row wise ; 
#                                           axis : 1 -> column wise ;

# one dimensational array : 
arr_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3] , [4,5,6]])
array_Md = np.array([[[1,2],[3,4],[5,6]],[[7,8],[1,2],[3,4]]])

print(arr_1d)
print(array_2d)
print(array_Md)


n_arr1 = np.insert(arr_1d,1,88);
print(n_arr1)
n_arr2=np.insert(array_2d,1,[1,1],axis = 1)
print(n_arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [1 2]
  [3 4]]]
[ 1 88  2  3  4  5]
[[1 1 2 3]
 [4 1 5 6]]


# Append data at the end of the arrray

In [7]:
# append the array 
# append(array,value)  it also returns a new array 


arr_1d = np.array([1,2,3,4,5])
array_2d = np.array([[1,2,3] , [4,5,6]])
array_Md = np.array([[[1,2],[3,4],[5,6]],[[7,8],[1,2],[3,4]]])

print(arr_1d)
print(array_2d)
print(array_Md)

newArr1 = np.append(arr_1d, [1,2,3]) # we can place the multiple values to append to the array.
print(newArr1)

newArr2 = np.append(arr_1d,1); # we can also do it with a single value to append.
print(newArr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]

 [[7 8]
  [1 2]
  [3 4]]]
[1 2 3 4 5 1 2 3]
[1 2 3 4 5 1]


# Concatenate the two or more array 

In [10]:
#concate 
# np.concatenate((array 1 , array 2 ) , axis = 0 )   --- we have to put the concatenating array in the tuple and then we have to define on what axis we have concatenate the array.

# axis = 0 -> vertical stacking 
# axis = 1 -> horizontal stacking 


arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

new_arr = np.concatenate((arr1,arr2),axis = 0)
#new_arr2 = np.concatenate((arr1,arr2),axis = 1)    --- we are not using this because it will show the error in this eg.


print(new_arr)
#print(new_arr2)



[1 2 3 4 5 6]


# Removing the Element from the numpy array --- using delete function

In [18]:
# np.delete(array , index , axis = None )        --- Here Axis NONE means we will remove the element from the flatten array 
# And It also returns a new array. and writing the axis is optional for default , but for some case can be used 


# 1D ARRAY
print("1D ARRAY",end="\n")
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

new_arr = np.delete(arr1,2,axis=None)
new_arr2 = np.delete(arr2,0,axis=0)

print(new_arr)
print(new_arr2)

# 2D ARRAY 
print("2D ARRAY",end="\n")

array_2d = np.array([[1,2,3] , [4,5,6]])
newArr2D = np.delete(array_2d , 0 , axis = 0 )
print(newArr2D)





1D ARRAY
[1 2]
[5 6]
2D ARRAY
[[4 5 6]]


# Stacking of Array   --- using vstack & hstack functions


In [22]:
# Stacking of Array 
# Either Vertically or Horizonally 
# vstack() row wise 
# hstack() column wise 

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

# And in both the functions we have to put the array in the form of tuple 

print(np.vstack((arr1,arr2))) # in this we are putting in vertically wise 
print(np.hstack((arr1,arr2))) # in this we are putting in horizontal wise 




[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# Splitting of Array --- using split() & hsplit & vsplit functions 

In [27]:
# n.split(array, 2 )     --- it split the array in equal parts , here we given 2 to tell how many parts we have divide it 
# np.vsplit()   --- it split the array in the vertical parts 
# np.hsplit()   --- it split the array in the horizontal parts 

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

mix = np.concatenate((arr1,arr2),axis=0)
# Note --- you should not put the value of dividing the array very high , it might give error.  
print(np.split(mix,2))



[array([1, 2, 3]), array([4, 5, 6])]


# BroadCasting & Vectorization 

In [29]:
# Broadcasting : we use it to prevent using loops , as loops are considers as slow in the acutal development area 

prices = np.array([100,200,400,2000])

discount = 20

finalPrice = prices - (prices * discount/100)

print(finalPrice)




[  80.  160.  320. 1600.]


# Single Value Broadcasting 

In [30]:
prices = np.array([100,200,400,2000])

discount = 20

result = prices * 2

print(result)


[ 200  400  800 4000]


# Dimensation Matching Broadcasting 

In [34]:
# we can also call it as 2D to 1D array broardcasting 

prices = np.array([[100,200,300,400],[5,6,7,8]])  # its a 2D array 

discount = np.array([10,15,20,25])    # its a 1D Array 

result = prices - (prices * discount/100)    

print(result)


[[ 90.  170.  240.  300. ]
 [  4.5   5.1   5.6   6. ]]


Broadcasing and vectorarisation both are little different things... In BroadCasting we use to expands the array to get the result. We use it for converting 1D array to 2D Array ... and in vectorization we do same but there are actually faster then the loops. and we use it in Matrix.

# Handling Missing & Special Values 

###  np.isnan(array) function --- For Finding the NAN values 

In [41]:
# NAN states not a number : and its returns the boolean values (true or false)
# its returns true value where there is no NAN condition

arr = np.array([1,2,np.nan,np.nan,5,6])

print(np.isnan(arr))

# we can directly compare the nan values 


[False False  True  True False False]


### np.nan_to_num(array,nan = value) --- For Changing the nan value to somethings else 

In [42]:


arr = np.array([1,2,np.nan,np.nan,5,6])

print(np.nan_to_num(arr,nan = 10))   # by default nan value is seted to 0 
 

[ 1.  2. 10. 10.  5.  6.]


### For Finding The infinite numbers --- using np.isinf(array)

In [47]:
arr = np.array([1,2,np.inf,-np.inf,5,6])

print(np.isinf(arr))  # here we can find the infinite values 

# if we have to replace the infinite values with somethings then we can do given below : 

replaced_inf = np.nan_to_num(arr,posinf=200,neginf=100) # Here posinf represents the postive infinite numbers , and neginf represents the negative infinite numbers 
print(replaced_inf)



[False False  True  True False False]
[  1.   2. 200. 100.   5.   6.]


# So Now The Numpy Is Finished .We Will Move Forward To The Projects After Completing Pandas.